site_name: Text Messages for Public Health
pages:
- Home: index.md
- Planning a campaign: planning.md
- Setting up a campaign: setting-up.md
- Writing messages: writing-messages.md
- Follow up: follow-up.md
- About: about.md
theme: readthedocs